HVC=read.csv(file.choose(),header=TRUE)
HVC.df=as.data.frame(HVC)
attach(HVC.df)
Subject=factor(Bird_Id)
Learner_type_HVC=factor(Learner_type)
Celltype_HVC=factor(Cell_type)
Hemisphere_HVC=factor(Hemisphere)
library(car)
library(lme4)
library(lmerTest)
HVC1=lmer(Density_interneurons~ Learner_type_HVC *Celltype_HVC *Hemisphere_HVC +(1|Subject),data=HVC.df, na.action=na.omit)
HVC2=lmer(Density_interneurons ~ Learner_type_HVC *Celltype_HVC+(1|Subject),data=HVC.df, na.action=na.omit )
HVC3=lmer(Density_interneurons ~ Celltype_HVC*Hemisphere_HVC + (1|Subject),data=HVC.df,na.action=na.omit)
HVC4=lmer(Density_interneurons~ Celltype_HVC + (1|Subject),data=HVC.df,na.action=na.omit)
HVC5= lmer(Density_interneurons~ Learner_type_HVC + (1|Subject),data=HVC.df,na.action=na.omit)
HVC6=lmer(Density_interneurons ~ Learner_type_HVC*Hemisphere_HVC +(1|Subject),data=HVC.df,na.action=na.omit)
HVC7=lmer(Density_interneurons ~ Celltype_HVC + Hemisphere_HVC +Celltype_HVC *Hemisphere_HVC + (1|Subject),data=HVC.df,na.action=na.omit)

HVC8=lmer(Density_interneurons ~  Hemisphere_HVC +Celltype_HVC + Celltype_HVC *Hemisphere_HVC + (1|Subject),data=HVC.df,na.action=na.omit)
HVC9=lmer(Density_interneurons ~ Celltype_HVC*Hemisphere_HVC + Learning_score + (1|Subject),data=HVC.df,na.action=na.omit)  
anova(HVC1,HVC2,HVC3,HVC4,HVC5)
summary(HVC1)
summary(HVC2)
summary(HVC3)
summary(HVC4)
summary(HVC5)
summary(HVC6)
summary(HVC7)
summary(HVC8)
summary(HVC9)
library(sjPlot)
plot_model(HVC1,type="int")
plot_model(HVC2,type="int")
plot_model(HVC3,type="int")
plot_model(HVC4,type="int")
plot_model(HVC5,type="int")
plot_model(HVC6,type="int")
plot_model(HVC7,type="int")
plot_model(HVC8,type="int")
