NCM=read.csv(file.choose(),header=TRUE)
NCM.df=as.data.frame(NCM)
attach(NCM.df)
Subject=factor(Bird_Id)
Learner_type_NCM=factor(Learner_type)
Celltype_NCM=factor(Cell_type)
Hemisphere_NCM=factor(Hemisphere)
library(car)
library(lme4)
library(lmerTest)
NCM1=lmer(Density_interneurons~ Learner_type_NCM *Celltype_NCM *Hemisphere_NCM +(1|Subject),data=NCM.df, na.action=na.omit)
NCM2=lmer(Density_interneurons ~ Learner_type_NCM *Celltype_NCM+(1|Subject),data=NCM.df, na.action=na.omit )
NCM3=lmer(Density_interneurons ~ Celltype_NCM*Hemisphere_NCM + (1|Subject),data=NCM.df,na.action=na.omit)
NCM4=lmer(Density_interneurons~ Celltype_NCM + (1|Subject),data=NCM.df,na.action=na.omit)
NCM5= lmer(Density_interneurons~ Learner_type_NCM + (1|Subject),data=NCM.df,na.action=na.omit)
NCM6=lmer(Density_interneurons ~ Learner_type_NCM*Hemisphere_NCM +(1|Subject),data=NCM.df,na.action=na.omit)
NCM7=lmer(Density_interneurons ~ Celltype_NCM + Hemisphere_NCM +Celltype_NCM *Hemisphere_NCM + (1|Subject),data=NCM.df,na.action=na.omit)

NCM8=lmer(Density_interneurons ~  Hemisphere_NCM +Celltype_NCM + Celltype_NCM *Hemisphere_NCM + (1|Subject),data=NCM.df,na.action=na.omit)
NCM9=lmer(Density_interneurons ~ Celltype_NCM*Hemisphere_NCM + Learning_score + (1|Subject),data=NCM.df,na.action=na.omit)  
anova(NCM1,NCM2,NCM3,NCM4,NCM5)
summary(NCM1)
summary(NCM2)
summary(NCM3)
summary(NCM4)
summary(NCM5)
summary(NCM6)
summary(NCM7)
summary(NCM8)
summary(NCM9)
library(sjPlot)
plot_model(NCM1,type="int")
plot_model(NCM2,type="int")
plot_model(NCM3,type="int")
plot_model(NCM4,type="int")
plot_model(NCM5,type="int")
plot_model(NCM6,type="int")
plot_model(NCM7,type="int")
plot_model(NCM8,type="int")
plot_model(NCM9,typ="int")
library(ggplot2)
ggplot(data=NCM.df, aes(Learner_type_NCM,Density_interneurons)) + geom_boxplot(aes(fill=Hemisphere_NCM))
NCM10=lmer(Density_interneurons~Learner_type_NCM + (1|Subject),data=NCM.df,na.action=na.omit) 
summary(NCM10)
